name = "esp32s3_psram"
description = "Use external PSRAM from Ada on the ESP32-S3 (a 1 MB array)"
version = "0.1.0-dev"

authors = ["D. Howells"]
maintainers = ["D. Howells <dhowells@motium.us>"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "esp32s3", "psram", "example"]

project-files = ["psram.gpr"]

[[depends-on]]
esp32s3_rts = "*"

[[pins]]
esp32s3_rts = { path = "../../crates/esp32s3_rts" }
xtensa_dynconfig       = { path = "../../crates/xtensa-dynconfig" }
