#!/usr/bin/env python3
"""Rasterise B612 into anti-aliased glyph atlases for the ST7789 text renderer,
at several sizes, covering printable Latin-1 (0x20..0xFF).

For each size it emits a C header of flat parallel arrays (clean to import into
Ada); each size is independent, so a build pays only for the sizes it references
(the C is compiled -fdata-sections).  It also emits:
  * b612_atlas.h      -- aggregator that #includes every size (for glue.c)
  * src/b612_<sz>.ads -- one Ada package per size, exposing a Glyph_Fonts.Font.

Coverage is 4-bit (16-level), 2 px/byte -- anti-aliased.

    ./gen_b612.py            # regenerate all sizes

Requires Pillow built with FreeType.  Re-run only when sizes/range/font change;
the committed headers + Ada packages are the build inputs.
"""
import os
from PIL import Image, ImageFont, ImageDraw

HERE  = os.path.dirname(os.path.abspath(__file__))
TTF   = os.path.join(HERE, "B612-Regular.ttf")
SIZES = (12, 16, 24)
FIRST, LAST = 0x20, 0xFF          # printable Latin-1; 0x7F..0x9F forced blank
COUNT = LAST - FIRST + 1


def rasterise(size):
    """Return (ascent, line_h, [per-glyph dict]) for one pixel size."""
    font = ImageFont.truetype(TTF, size)
    ascent, descent = font.getmetrics()
    line_h = ascent + descent
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = round(font.getlength(ch))
        blank = 0x7F <= code <= 0x9F           # DEL + C1 controls: no glyph
        if blank:
            glyphs.append(dict(adv=adv, w=0, h=0, xoff=0, yoff=0, mask=None))
            continue
        pad, base = 8, ascent + 6
        canvas = Image.new("L", (size * 3 + 2 * pad, line_h + 2 * pad), 0)
        ImageDraw.Draw(canvas).text((pad, base), ch, font=font, fill=255, anchor="ls")
        bbox = canvas.getbbox()
        if bbox is None:                       # blank (space, nbsp)
            glyphs.append(dict(adv=adv, w=0, h=0, xoff=0, yoff=0, mask=None))
            continue
        l, t, r, b = bbox
        glyphs.append(dict(adv=adv, w=r - l, h=b - t, xoff=l - pad, yoff=t - base,
                           mask=list(canvas.crop(bbox).getdata())))
    return ascent, line_h, glyphs


def pack(glyphs):
    """4-bit coverage, 2 px/byte; fill each glyph's 'off' (byte offset)."""
    bits = bytearray()
    for g in glyphs:
        g["off"] = len(bits)
        if g["mask"] is None:
            continue
        m = g["mask"]
        for i in range(0, len(m), 2):
            hi = m[i] >> 4
            lo = (m[i + 1] >> 4) if i + 1 < len(m) else 0
            bits.append((hi << 4) | lo)
    return bits


def carr(name, vals, ctype, perline=24):
    out = [f"const {ctype} {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), perline):
        out.append("  " + ",".join(str(v) for v in vals[i:i + perline]) + ",")
    out.append("};")
    return "\n".join(out)


def emit_c(tag, glyphs, bits):
    L = [f"/* Auto-generated by gen_b612.py from B612-Regular.ttf (SIL OFL 1.1).",
         f"   variant '{tag}', anti-aliased 4-bit, Latin-1 0x{FIRST:02X}..0x{LAST:02X}.",
         f"   Do not edit. */",
         carr(f"{tag}_adv",  [g["adv"]  for g in glyphs], "unsigned char"),
         carr(f"{tag}_w",    [g["w"]    for g in glyphs], "unsigned char"),
         carr(f"{tag}_h",    [g["h"]    for g in glyphs], "unsigned char"),
         carr(f"{tag}_xoff", [g["xoff"] for g in glyphs], "signed char"),
         carr(f"{tag}_yoff", [g["yoff"] for g in glyphs], "signed char"),
         carr(f"{tag}_off",  [g["off"]  for g in glyphs], "unsigned short", 16),
         carr(f"{tag}_bits", list(bits), "unsigned char"),
         f"const int {tag}_len = (int) sizeof({tag}_bits);"]
    open(os.path.join(HERE, f"{tag}.h"), "w").write("\n".join(L) + "\n")


def emit_ada(tag, pkg, size, ascent, line_h, nbytes):
    A = [f"--  Auto-generated by gen_b612.py -- do not edit.  One B612 atlas size:",
         f"--  {size} px, anti-aliased (4-bit), Latin-1 0x{FIRST:02X}..0x{LAST:02X}",
         f"--  ({nbytes} bytes of glyph data).  The arrays are defined in glue.c via",
         f"--  #include \"{tag}.h\".  'with' this package only if you use this size --",
         f"--  otherwise its data is never linked.",
         "with Glyph_Fonts; use Glyph_Fonts;",
         "with System;",
         "",
         f"package {pkg} is",
         f"   {tag}_adv  : constant Byte_Array (0 .. {COUNT - 1});  pragma Import (C, {tag}_adv,  \"{tag}_adv\");",
         f"   {tag}_w    : constant Byte_Array (0 .. {COUNT - 1});  pragma Import (C, {tag}_w,    \"{tag}_w\");",
         f"   {tag}_h    : constant Byte_Array (0 .. {COUNT - 1});  pragma Import (C, {tag}_h,    \"{tag}_h\");",
         f"   {tag}_xoff : constant SByte_Array (0 .. {COUNT - 1}); pragma Import (C, {tag}_xoff, \"{tag}_xoff\");",
         f"   {tag}_yoff : constant SByte_Array (0 .. {COUNT - 1}); pragma Import (C, {tag}_yoff, \"{tag}_yoff\");",
         f"   {tag}_off  : constant U16_Array (0 .. {COUNT - 1});   pragma Import (C, {tag}_off,  \"{tag}_off\");",
         f"   {tag}_bits : constant Byte_Array (0 .. {nbytes - 1}); pragma Import (C, {tag}_bits, \"{tag}_bits\");",
         f"   Font : constant Glyph_Fonts.Font :=",
         f"     (First => {FIRST}, Count => {COUNT}, Height => {line_h}, Ascent => {ascent},",
         f"      Adv  => {tag}_adv'Address,  W    => {tag}_w'Address,    H    => {tag}_h'Address,",
         f"      XOff => {tag}_xoff'Address, YOff => {tag}_yoff'Address, Off  => {tag}_off'Address,",
         f"      Bits => {tag}_bits'Address);",
         f"   Bytes : constant := {nbytes};",
         f"end {pkg};"]
    open(os.path.join(HERE, "..", "src", f"{pkg.lower()}.ads"), "w").write("\n".join(A) + "\n")


def main():
    tags = []
    for size in SIZES:
        ascent, line_h, glyphs = rasterise(size)
        bits = pack(glyphs)
        tag  = f"b612_{size}"
        emit_c(tag, glyphs, bits)
        emit_ada(tag, f"B612_{size}", size, ascent, line_h, len(bits))
        tags.append(tag)
        print(f"{tag}: {COUNT} glyphs, {len(bits):5d} bytes  (ascent {ascent}, line {line_h})")

    inc = ["/* Auto-generated: every B612 size.  For a demo that shows them all -- a",
           "   real app #includes just the sizes it uses, so the rest aren't compiled. */"]
    inc += [f'#include "{t}.h"' for t in tags]
    open(os.path.join(HERE, "b612_atlas.h"), "w").write("\n".join(inc) + "\n")
    print("wrote b612_atlas.h and src/b612_<size>.ads (one per size)")


if __name__ == "__main__":
    main()
