/* esp32s3_b612 B612 glyph atlases.

   The atlases (b612_atlas.h, generated by the shared tools/gen_font.py from
   B612-Regular.ttf -- see main/regen.sh) are #included here so their flat arrays
   get external linkage; the generated Ada packages (src/b612_<sz>.ads) import
   them and the HAL text engine (ESP32S3.ST7789.Fonts) renders glyphs by
   alpha-blending against a known background.  Console output is now formatted in
   Ada via ESP32S3.Log.  Bare-boot is shared in ../../common/bare/bare_glue.c. */

#include "b612_atlas.h"   /* every B612 size (12/16/24 px), anti-aliased */
