/* esp32s3_b612 example console helper + B612 glyph atlas.

   The atlas (b612_24.h, generated by gen_b612.py from B612-Regular.ttf) is
   #included here so its flat arrays get external linkage; the Ada side imports
   them (src/main.adb) and renders glyphs by alpha-blending against a known
   background.  Bare-boot is shared in ../../common/bare/bare_glue.c. */
extern int esp_rom_printf(const char *fmt, ...);

#include "b612_atlas.h"   /* every B612 size (12/16/24 px), anti-aliased */

void native_b612_banner(void)
{
    esp_rom_printf("[b612] anti-aliased B612 font: 12/16/24 px "
                   "-> ST7789 240x240\n");
}

void native_b612_size(const char *name, int bytes)
{
    esp_rom_printf("[b612]   %-8s %5d bytes\n", name, bytes);
}
