name = "esp32s3_es8311"
description = "Bare-metal Ada I2S ES8311 codec 440Hz audio-output test"
version = "0.1.0-dev"

authors = ["D. Howells"]
maintainers = ["D. Howells <dhowells@motium.us>"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "esp32s3", "i2s", "ES8311 codec 440Hz audio-output test"

project-files = ["i2s_ES8311 codec 440Hz audio-output test"

[[depends-on]]
esp32s3_rts = "*"

[[pins]]
esp32s3_rts = { path = "../../crates/esp32s3_rts" }
xtensa_dynconfig       = { path = "../../crates/xtensa-dynconfig" }
